import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";
import { SiteHeader } from "@/components/header/SiteHeader";
import { Toaster } from "@/components/ui/toaster";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Theme>
            <NextTopLoader
              height={2}
              color="rgb(156, 163, 175, 0.9)"
              showSpinner={false}
            />
            <SiteHeader />
            {children}
            <SpeedInsights />
            <Analytics />
          </Theme>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
